### DISCUSSION TITLE
Set state of ON_OFF_SWITCH

### DISCUSSION THREAD

**Discussion by rot169** [luar123/zigbee_esphome#18] [Q&A] [answered]
Hello!

I don't seem to be able to set the state of a switch. Not sure if this is me doing something wrong, or if this is just not implemented yet!?

I have two endpoints defined:
```
zigbee:
  id: "zb"
  endpoints:
    - device_type: TEMPERATURE_SENSOR
      num: 1
      clusters:
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              id: zb_temp
              value: 0
    - device_type: ON_OFF_SWITCH
      num: 2
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0x0
              type: BOOL
              report: true
              id: zb_switch
              value: false
```

I'm able to successfully set the temperature value:
```
      - zigbee.setAttr:
          id: zb_temp
          value: !lambda "return x;"
```

But I can't do the same to set the switch state:
```
      - zigbee.setAttr:
          id: zb_switch
          value: true
```

I get the following build error:
```
src/main.cpp:34:29: error: template argument 2 is invalid
   34 | zigbee::SetAttrAction<bool, > *zigbee_setattraction_id_2;
      |                             ^
src/main.cpp: In function 'void setup()':
src/main.cpp:391:63: error: template argument 2 is invalid
  391 |   zigbee_setattraction_id_2 = new zigbee::SetAttrAction<bool, >(zb_heat_a);
      |                                                               ^
src/main.cpp:391:35: error: expected type-specifier
  391 |   zigbee_setattraction_id_2 = new zigbee::SetAttrAction<bool, >(zb_heat_a);
      |                                   ^~~~~~
src/main.cpp:392:30: error: request for member 'set_value' in '* zigbee_setattraction_id_2', which is of non-class type 'int'
  392 |   zigbee_setattraction_id_2->set_value(true);
      |                              ^~~~~~~~~
src/main.cpp:393:31: error: cannot convert '<brace-enclosed initializer list>' to 'const std::vector<esphome::Action<>*, std::allocator<esphome::Action<>*> >&'
  393 |   automation_id_7->add_actions({light_lightcontrolaction_id, lambdaaction_id_2, zigbee_setattraction_id_2});
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Any ideas?

Thanks!!

**Comment by luar123** [comment]
Switches (for controlling other ZB devices)are not supported. But you could try a binary sensor instead and use a automation in HA instead.
The build errors are strange, but seem to be related to something different (zb_heat_a).

**Reply by luar123** [reply, marked as answer]
I found a work around to make switches work with some lambdas and zigbee sdk knowledge:

1. add the needed client clusters, for some switches those can be added by simply adding an endpoint with the correct device id:
```
endpoints:
    - num: 4
      device_type: ON_OFF_SWITCH
```
2. Then look up the correct commands and create a lambda. Toggle command for on_off switch is:
```
on_press:
      then:
        #- zigbee.report: zb
        - lambda: |-
            esp_zb_zcl_on_off_cmd_t cmd_req;
            cmd_req.zcl_basic_cmd.src_endpoint = 4; // switch endpoint, same as ep definition
            cmd_req.address_mode = ESP_ZB_APS_ADDR_MODE_DST_ADDR_ENDP_NOT_PRESENT;
            cmd_req.on_off_cmd_id = ESP_ZB_ZCL_CMD_ON_OFF_TOGGLE_ID; // toggle command
            esp_zb_lock_acquire(portMAX_DELAY);
            esp_zb_zcl_on_off_cmd_req(&cmd_req); //send on_off cluster command
            ESP_LOGI("test", "Send cmd!");
            esp_zb_lock_release();
```
You need to bind the on_off cluster to the device you want to control. This can be done through the coordinator.

**Reply by rot169** [reply]
Ah nice, I'll go explore that route - thanks!

**Reply by MTRNord** [reply]
Hm 2 questions: 

In my case I would love to have a toggle switch of a CO2 traffic light thing. So the switches equal the LEDs basically meaning its more of a toggle than a press. and I am wondering how to do this here. I think it does that?

The other one is I got 3 of those. Do I just use 3 endpoints?

**Reply by luar123** [reply]
3 endpoints are needed, yes.
The rest I didn't get. You have a esphome CO2 sensor that should control another zigbee light?

**Comment by rot169** [comment]
Oh, I'd renamed `zb_heat_a` to `zb_switch` in the config for posting; they're the same thing. But if switches arent implemented, then no surprise there's a build error! Using HA as you describvd would be functional, although my end goal here is to set up a binding so this device is able to directly alter the state of an on/off relay without a dependancy on HA, the server it sits n, or the network between my coordinator and HA :) I'm wondering if the same solution from https://github.com/luar123/zigbee_esphome/discussions/16 will work for my use case too... will give that a try over the next few days.

**Reply by luar123** [reply]
Ok, no that is not implemented.

No, I don't think that would help. he wanted to create a switch entity in HA to control an output.

**Reply by rot169** [reply]
Ah, shame! I'm motivated to throw some cycles at building this, but I'm still trying to wrap my head around the nuances of both zigbee and esphome... so if you had any pointers on what's needed at a high level to achieve this I'd be up for giving it a try!

**Reply by luar123** [reply]
Basically it should be pretty easy: You need to define the client clusters (if there is a matching switch device_type that is done automatically) and you need to bind the device, but this can be handled through the coordinator and then you just need to send the correct command instead of setting an attribute (see for example [here](https://github.com/espressif/arduino-esp32/blob/a81e2d48f57c0a4c0b90c4a06596904d0905805a/libraries/Zigbee/src/ep/ZigbeeSwitch.cpp#L66)).
The difficult part is how to set this up in a generic way. I would probably create a new `zigbee.sendCmd` action, just like `zigbee.setAttr` and then you need to find a good way to generate all the different command, including their configuration. Maybe using an enum and switches like in `zigbee_helpers.c` (This file is generated from sdk source files with https://github.com/luar123/zigbee_esphome/blob/master/components/zigbee/files_to_parse/parse_zigbee_headers.py).
Here are all the commands and structs/enums: https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/api-reference/zcl/esp_zigbee_zcl_command.html#

**Comment by rot169** [comment]
P.S. I saw "time sync" was on yor TODO list @luar123... had you made much progress on this? I was playing with this yesterday and have a basic implementation working. Will send a PR over once I've got it tidied-up and integrated into the `time` component, if that'd be of use?

**Reply by luar123** [reply]
Yes, please create a PR.

**Comment by riccardo-sala** [comment]
Hello, I made a simple Zigbee button with a C6 board following the solution proposed by luar123 that is joined  to my zigbee2mqtt network .

The button is paired with an IKEA bulb, it works **very well** even if the zigbee2mqtt coordinator is down.

Here is the code:

```
esphome:
  name: zb-button

esp32:
 board: esp32-c6-devkitm-1
 variant: esp32c6
 partitions: partitions_zb.csv
 framework:
   type: esp-idf
   sdkconfig_options:
     CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y


# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: VERBOSE

external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

zigbee:
  id: zb
  manufacturer: RS
  endpoints:
    - num: 1
      device_type: ON_OFF_SWITCH

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: 9
      ignore_strapping_warning: true
      mode:
        input: true
        pullup: true
      inverted: true
    id: boot_button
    name: "Boot button"
    on_press:
      then:
        - zigbee.report: zb
        - lambda: |-
            esp_zb_zcl_on_off_cmd_t cmd_req;
            cmd_req.zcl_basic_cmd.src_endpoint = 1; // switch endpoint, same as ep definition
            cmd_req.address_mode = ESP_ZB_APS_ADDR_MODE_DST_ADDR_ENDP_NOT_PRESENT;
            cmd_req.on_off_cmd_id = ESP_ZB_ZCL_CMD_ON_OFF_TOGGLE_ID; // toggle command
            esp_zb_lock_acquire(portMAX_DELAY);
            esp_zb_zcl_on_off_cmd_req(&cmd_req); //send on_off cluster command
            ESP_LOGI("test", "Send cmd!");
            esp_zb_lock_release();
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb
```
It works, but every 30 seconds I get this message on the esp32 console:

```
[20:41:12.848][D][zigbee:293][Zigbee_main]: No attributes configured for report (endpoint 1; cluster 0x0006; attribute id 0x0000)
[20:41:43.138][D][zigbee:293][Zigbee_main]: No attributes configured for report (endpoint 1; cluster 0x0006; attribute id 0x0000)
[20:42:13.428][D][zigbee:293][Zigbee_main]: No attributes configured for report (endpoint 1; cluster 0x0006; attribute id 0x0000)
[20:42:43.717][D][zigbee:293][Zigbee_main]: No attributes configured for report (endpoint 1; cluster 0x0006; attribute id 0x0000)

```
I apologize for my ignorance, I searched the documentation but I didn't understand what I should do to fix it.
Any suggestions are very welcome!
Thanks!!
