### DISCUSSION TITLE
HowTo Deep Sleep?

### DISCUSSION THREAD

**Discussion by baal86** [luar123/zigbee_esphome#32] [Q&A] [answered]
Hello,

I am playing around with deep sleep but can't get it to work. I have an H2 board and a C6 board. Esphome does not support deep sleep on the H2 so I am using the C6. I have a naive config with just a temperature sensor and a fake pressure sensor that increments on button press. The code below (without deep sleep) works great! If I add a basic deep sleep statement with 1s on time and 10s off time, the device gets stuck at boot. I will need to hold BOOT and reprogram it to get it back to life. 

Anyone has experience with deep sleep and zigbee? My final application only needs to send one sensor value every 10 minutes or so and I'd like tp spend the time inbetween sleeping to be maybe able to run from battery

baal86

```
esphome:
  name: zb-example-c6

esp32:
  board: esp32-c6-devkitc-1
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    version: latest

external_components:
  - source:
      type: git
      url: https://github.com/luar123/zigbee_esphome
      ref: "master"
    refresh: 0s
    components: [zigbee]

globals:
  - id: counter
    type: int
    restore_value: no
    initial_value: '0.0'

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    id: "temp"
    filters:
      - delta: 0.1
  - platform: template
    name: "Template Sensor"
    id: "press"
    lambda: "return id(counter);"
    update_interval: 60s


zigbee:
  id: "zb"
  endpoints:
    - device_type: TEMPERATURE_SENSOR
      num: 1
      clusters:
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temp
              scale: 100
        - id: PRESSURE_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: press
              scale: 100

binary_sensor:
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - lambda: "id(counter) += 100;"
        - zigbee.report: zb
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb
```

**Comment by luar123** [comment, marked as answer]
I did not test deepsleep (and I have only a H2, so someone needs to add a PR for adding this first).
I would expect it to just work, but maybe I need to block deepsleep during zigbee setup.

Anyway, deepsleep is not really ideal for zigbee because it needs to connect to the network each time which takes much longer than 1s, I guess. Lightsleep would be much better, but is not supported by esphome.
Try to set on time to 1 minute and if that works try to reduce it.

**Reply by baal86** [reply]
OK! Saw that the C6 devkit for some reason does not have a 32kHz RTC clock which is, of course, required for the cPU to wake up again.

**Reply by luar123** [reply]
Just had a quick look at the deepsleep component: H2 is not handeled correctly, but that would be an easy fix.
C6 and H2 both have Internal 136 kHz RC Oscillator that is used by default, so that should work. Maybe try a simple example without ZigBee first. Or ask in discord, there is a big thread about C6.

**Reply by baal86** [reply]
Yes, I am aware of H2 not being fully supported at the moment. I raised the issue there. If I can get my head around the esphome build system and dust off my C++ I'll fix it myself and then submit it as a patch.

I'll continue experimenting with Zigbee + deep sleep on C6 then. (starting with confirming the C6 deep sleep actually works!) I had hoped someone had already tried it with this component.

**Reply by baal86** [reply]
Got something working. It will wake up every minute and send data for 10s. I discovered that if I force report zigbee I can get quite a few samples out in that 10s period. I have made a GPIO wakeup as well that gives a minute so that zigbee configuration works. All of it implemented on the C6. Now need to look into the H2 or hope for the maintainers to get to it. I think I will underclock the C6 and see what power consumption I get there.

```
esphome:
  name: zb-example-c6

esp32:
  board: esp32-c6-devkitc-1
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    version: latest

deep_sleep:
  run_duration:
    gpio_wakeup_reason: 60s
    default: 10s
  sleep_duration: 50s
  wakeup_pin: 2
  wakeup_pin_mode: INVERT_WAKEUP


external_components:
  - source:
      type: git
      url: https://github.com/luar123/zigbee_esphome
      ref: "master"
    refresh: 0s
    components: [zigbee]

globals:
  - id: counter
    type: int
    restore_value: yes
    initial_value: "0"

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    id: "temp"
    filters:
      - delta: 0.1
  - platform: template
    name: "Template Sensor"
    id: "press"
    lambda: "return int(rand() % 100 + 100);"
    update_interval: 1s
    on_value: 
      then:
        zigbee.report: zb

zigbee:
  id: "zb"
  endpoints:
    - device_type: TEMPERATURE_SENSOR
      num: 1
      clusters:
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temp
              scale: 100
        - id: PRESSURE_MEASUREMENT
          attributes:
            - attribute_id: 0
              id: pressure_attr
              type: S16
              report: true
              value: 100
              device: press

binary_sensor:
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_click:
      min_length: 3s
      max_length: 20s
      then:
        - zigbee.reset
```

**Reply by baal86** [reply]
FYI: Started tinkering with the deep sleep feature of the H2. https://github.com/baal86/esphome/ It does not have GPIO wakeup so the external pin wakeup needs to be implemented using EXT1

**Reply by luar123** [reply]
Interesting, I thought you could just re-use the implementation of C6.

**Reply by baal86** [reply]
Got it running. Pull request ongoing at esphome. The H2 is impressive. With Zigbee active, current consumption is around 10-15mA. When in deep sleep not measurable (with the stuff I have at home at least..). I can very reliably get samples out with just 10s wake time.

```
esphome:
  name: zb-example-h2b

esp32:
  board: esp32-h2-devkitm-1
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    version: latest

external_components:
  - source:
      type: git
      url: https://github.com/luar123/zigbee_esphome
      ref: "master"
    refresh: 0s
    components: [zigbee]
  - source:
      type: git
      url: https://github.com/baal86/esphome
      ref: "dev"
    refresh: 0s
    components: [deep_sleep]

deep_sleep:
  run_duration:
    gpio_wakeup_reason: 60s
    default: 10s
  sleep_duration: 50s
  esp32_ext1_wakeup:
    pins:
      - 10
    mode: ANY_HIGH

globals:
  - id: counter
    type: int
    restore_value: yes
    initial_value: "0"

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    id: "temp"
    filters:
      - delta: 0.1
  - platform: template
    name: "Template Sensor"
    id: "press"
    lambda: "return int(rand() % 100 + 100);"
    update_interval: 1s
    on_value: 
      then:
        zigbee.report: zb

zigbee:
  id: "zb"
  endpoints:
    - device_type: TEMPERATURE_SENSOR
      num: 1
      clusters:
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temp
              scale: 100
        - id: PRESSURE_MEASUREMENT
          attributes:
            - attribute_id: 0
              id: pressure_attr
              type: S16
              report: true
              value: 100
              device: press

binary_sensor:
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_click:
      min_length: 3s
      max_length: 20s
      then:
        - zigbee.reset
```
