### DISCUSSION TITLE
Grow R503 fingerprint sensor using Zigbee

### DISCUSSION THREAD

**Discussion by Ma1ch** [luar123/zigbee_esphome#37] [General]
Hey,

Has anyone been able to implement the grow R503 fingerprint sensor but with a esp32c6 using zigbee? I have been able to get it done with wifi, but transferring this to zigbee version is proving challenging.

```
esphome:
  name: fingerprint
  friendly_name: Fingerprint

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging with debug level
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: ""

  services:
    - service: enroll
      variables:
        finger_id: int
        num_scans: int
      then:
        - logger.log: "Starting enrollment for finger_id {{ finger_id }} with {{ num_scans }} scans."
        - fingerprint_grow.aura_led_control:
            state: FLASHING
            speed: 50
            color: BLUE
            count: 10  # Flashing blue during enrollment process
        - fingerprint_grow.enroll:
            finger_id: !lambda 'return finger_id;'
            num_scans: !lambda 'return num_scans;'
    - service: enroll_next
      variables:
        num_scans: int
      then:
        - logger.log: "Starting enrollment for the next available slot with {{ num_scans }} scans."
        - fingerprint_grow.aura_led_control:
            state: FLASHING
            speed: 50
            color: BLUE
            count: 10  # Flashing blue during enrollment process
        - fingerprint_grow.enroll:
            finger_id: !lambda 'return id(fingerprint_count).state;'
            num_scans: !lambda 'return num_scans;'
    - service: cancel_enroll
      then:
        - logger.log: "Enrollment process cancelled."
        - fingerprint_grow.aura_led_control:
            state: ALWAYS_ON
            speed: 0
            color: RED
            count: 0
        - fingerprint_grow.cancel_enroll:
    - service: delete
      variables:
        finger_id: int
      then:
        - logger.log: "Deleting fingerprint with finger_id {{ finger_id }}."
        - fingerprint_grow.aura_led_control:
            state: FLASHING
            speed: 50
            color: PURPLE
            count: 5
        - fingerprint_grow.delete:
            finger_id: !lambda 'return finger_id;'
    - service: delete_all
      then:
        - logger.log: "Deleting all fingerprints."
        - fingerprint_grow.aura_led_control:
            state: FLASHING
            speed: 50
            color: RED
            count: 10
        - fingerprint_grow.delete_all:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true  # Ensures faster reconnection to the WiFi network if signal drops.
  ap:
    ssid: "Fingerprint Fallback Hotspot"
    password: "somepasswordxxx**"

bluetooth_proxy:
  active: true  

captive_portal:

uart:
  tx_pin: GPIO17 # ESP32 TX pin
  rx_pin: GPIO16 # ESP32 RX pin
  baud_rate: 57600

fingerprint_grow:
  sensing_pin: GPIO4

  on_finger_scan_matched:
    - logger.log: "Fingerprint matched with an enrolled fingerprint."
    - fingerprint_grow.aura_led_control:
        state: BREATHING
        speed: 200
        color: BLUE
        count: 1
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Authorized finger"
    - delay: 3s
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Scan your finger"
  
  on_finger_scan_unmatched:
    - logger.log: "Fingerprint scan did not match any enrolled fingerprint."
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Unauthorized finger"
    - delay: 3s
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Scan your finger"
  
  on_enrollment_scan:
    - logger.log: "Fingerprint scanned for enrollment."
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: BLUE
        count: 2
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Finger scanned"
  
  on_enrollment_done:
    - logger.log: "Fingerprint successfully enrolled!"
    - fingerprint_grow.aura_led_control:
        state: BREATHING
        speed: 100
        color: GREEN  # Switch to green to indicate successful enrollment
        count: 3
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Enrolled fingerprint"
  
  on_enrollment_failed:
    - logger.log: "Enrollment failed."
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 4
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Failed to enroll fingerprint"

text_sensor:
  - platform: template
    id: fingerprint_state
    name: "Garage Fingerprint State"

sensor:
  - platform: fingerprint_grow
    fingerprint_count:
      name: "Garage Fingerprint Count"
      id: fingerprint_count
    last_finger_id:
      name: "Garage Fingerprint Last Finger ID"
    last_confidence:
      name: "Garage Fingerprint Last Confidence"
    status:
      name: "Garage Fingerprint Status"
    capacity:
      name: "Garage Fingerprint Capacity"
    security_level:
      name: "Garage Fingerprint Security Level"

ota:
  platform: esphome
  password: !secret api_password

safe_mode:  # Safe mode without the 'enable' option
```

Any tips on the structure would be appreciated!
