### DISCUSSION TITLE
How do I prevent it from sending 0 on startup?

### DISCUSSION THREAD

**Discussion by MTRNord** [luar123/zigbee_esphome#42] [Q&A]
Hi :) I am trying to make myself a zigbee co2 traffic light. On startup some sensors seem to report 0 or unknown. I am "fetching" from the sensor using zigbee2mqtt and it seems like on startup it receives the value 0 as defaults. Instead I would prefer it to not send that and wait for a "real" value. In my case something greater than 0. I am however unsure how to do that.

Edit: Thanks for taking the time btw to make this a thing. It helps a lot <3

For reference this is my setup:

```
esphome:
  name: esphome-web-aea8c8
  friendly_name: Marcel CO2 Ampel Büro
  min_version: 2025.4.0
  name_add_mac_suffix: false


external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

#deep_sleep:
#  run_duration:
#    gpio_wakeup_reason: 60s
#    default: 20s
#  sleep_duration: 50s
#  wakeup_pin: 2
#  wakeup_pin_mode: INVERT_WAKEUP

esp32:
  board: esp32-c6-devkitm-1
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_2MB: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_ESPTOOLPY_FLASHSIZE: "4MB"
      CONFIG_PARTITION_TABLE_CUSTOM: y
      CONFIG_PARTITION_TABLE_OFFSET: y
      CONFIG_PARTITION_TABLE_MD5: y
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXX"

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE

# Zigbee button
binary_sensor:
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - logger.log: "Resetting zigbee"
        - zigbee.reset: zb
        - logger.log: "Reset zigbee"
  - platform: template
    name: "Red Status LED"
    id: button_red
    internal: true
    on_state:
      - zigbee.report: zb
  - platform: template
    name: "Yellow Status LED"
    id: button_yellow
    internal: true
    on_state:
      - zigbee.report: zb
  - platform: template
    name: "Green Status LED"
    id: button_green
    internal: true
    on_state:
      - zigbee.report: zb

switch:
  - platform: gpio
    pin: GPIO18
    internal: true
    id: switch_red
    name: "Red Status LED"
  - platform: gpio
    pin: GPIO20
    internal: true
    id: switch_yellow
    name: "Yellow Status LED"
  - platform: gpio
    pin: GPIO19
    internal: true
    id: switch_green
    name: "Green Status LED"


zigbee:
  id: "zb"
  manufacturer: "MTRNord"
  endpoints:
    - num: 1
      device_type: TEMPERATURE_SENSOR
      clusters:
        - id: CARBON_DIOXIDE_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: SINGLE
              device: co2val
              report: true
            - attribute_id: 0x0002
              type: SINGLE
              report: true
              value: 5000
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              device: tempval
              scale: 100
    # These really should be lights/lamps but I am clearly not able to do that here?!
    - num: 2
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: BINARY_INPUT
          attributes:
            - attribute_id: 0x0055
              type: bool
              report: true
              device: button_green
              id: zb_green_switch
    - num: 3
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: BINARY_INPUT
          attributes:
            - attribute_id: 0x0055
              type: bool
              report: true
              device: button_yellow
              id: zb_yellow_switch
    - num: 4
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: BINARY_INPUT
          attributes:
            - attribute_id: 0x0055
              type: bool
              report: true
              device: button_red
              id: zb_red_switch
  on_join:
    then:
      - logger.log: "Joined network"

captive_portal:

# Serielle Schnittstelle definieren
uart:
  rx_pin: GPIO22
  tx_pin: GPIO23
  baud_rate: 9600

# Sensor konfigurieren
sensor:
# Wi-Fi signal strength sensor
  - platform: wifi_signal
    name: "Marcel CO2 Ampel Büro WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    on_value:
      then:
        zigbee.report: zb
  - platform: uptime
    name: "Marcel CO2 Ampel Büro Uptime"
    on_value:
      then:
        zigbee.report: zb
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Marcel CO2 Ampel Büro WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
  # CO2 Sensor
  - platform: mhz19
    co2:
      internal: true
      name: "Marcel Buero MH-Z19 CO2 Value" #Entity-ID in HA
      id: co2val          
      on_value_range: # Schwellwerte für die Ampel
        - below: 1200
          then:
            - switch.turn_on: switch_green
            - binary_sensor.template.publish:
                id: button_green
                state: ON
            - switch.turn_off: switch_yellow
            - binary_sensor.template.publish:
                id: button_yellow
                state: OFF
            - switch.turn_off: switch_red
            - binary_sensor.template.publish:
                id: button_red
                state: OFF
            - zigbee.report: zb
        - above: 1200
          then:
            - switch.turn_off: switch_green
            - binary_sensor.template.publish:
                id: button_green
                state: OFF
            - switch.turn_on: switch_yellow
            - binary_sensor.template.publish:
                id: button_yellow
                state: ON
            - switch.turn_off: switch_red
            - binary_sensor.template.publish:
                id: button_red
                state: OFF
            - zigbee.report: zb
        - above: 1800
          then:
            - switch.turn_off: switch_green
            - binary_sensor.template.publish:
                id: button_green
                state: OFF
            - switch.turn_off: switch_yellow
            - binary_sensor.template.publish:
                id: button_yellow
                state: OFF
            - switch.turn_on: switch_red
            - binary_sensor.template.publish:
                id: button_red
                state: ON
            - zigbee.report: zb
    temperature:
      name: "Marcel Buero MH-Z19 Temperature"
      internal: true
      id: tempval
      on_value:
        then:
          zigbee.report: zb
    update_interval: 60s
    automatic_baseline_calibration: true
    id: sens1
```

Curently this leads to this graph:

Until 17:00 it was offline/unplugged. After 17:00 it was plugged in and sent 0. After startup it then continued to report normal. On the second restart at 18:15 it did the 0 again until it was up.

![image](https://github.com/user-attachments/assets/da479f6e-3639-48fe-8d15-97bb1e57d9ad)
