### ISSUE TITLE
Not able to install - "ESP32-H2" vs. "ESP32H2"

### ISSUE THREAD

**Issue by stefangries** [luar123/zigbee_esphome#12]
I'm using a basic yaml to try to install my ESP-32-H2-DevKit:

```
esphome:
  name: zig3

external_components:
  - source: components
    components: [ zigbee ]

esp32:
  board: esp32-h2-devkitm-1
  flash_size: 4MB
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    version: 5.1.4
    source: https://github.com/pioarduino/esp-idf/releases/download/v5.1.4.240921/esp-idf-v5.1.4.zip
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.05/platform-espressif32.zip
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
  variant: esp32h2
```

When trying to install it, I get this error:
![image](https://github.com/user-attachments/assets/6ab830a0-b49e-4b84-8a16-57262a10c654)

When not using a yaml to install and instead using the "+ New Device" button, I get this:
![image](https://github.com/user-attachments/assets/c1715f2e-0dc8-46e6-a9d5-35dffd66a83f)

Seems like the device identifies as "ESP32-H2" while the yaml expects an "ESP32H2". Where is my mistake? What can I do to install? Is this a bug?
