### ISSUE TITLE
Can't configure power source on initial network enrollment

### ISSUE THREAD

**Issue by Sharp398** [luar123/zigbee_esphome#28]
Hi there,

I'm trying to setup an ESP32-C6 as a battery-based device with deep-sleep to initialize once every hour to take some measurements, including battery state, and report it to HA via ZHA.

I've gotten the device to boot and successfully enroll in the ZHA network and report things like temperature and humidity from an AHT20. However, in Home Assistant the device does not appear to display any battery entity. I suspect it's because the ZHA integration reports the Power Source is Mains, so HA does not assume there's a battery entity.

![Image](https://github.com/user-attachments/assets/5909ccf3-9ea6-4adf-a0b2-5a51d272bfea)

I've tried to configure the `power_supply: 0x03` under the `zigbee` configuration in the esphome yaml file, as the ZCL reports that 0x03 is the enum for battery. I've even tried to manually configure the `BASIC` cluster with the Power Source attribute and the `POWER_CONFIG` as follows:
```
        - id: POWER_CONFIG                                                                                                 
          attributes:                                                                                                      
            - attribute_id: 0x0020 # Battery Voltage                                                                       
              type: U8                                                                                                     
              report: true                                                                                                 
              id: v_batt                                                                                                   
              value: 255                                                                                                   
              access: read_only                                                                                            
            - attribute_id: 0x0021 # Battery Percentage                                                                    
              type: U8                                                                                                     
              report: true                                                                                                 
              id: batt_percent                                                                                             
              value: 255                                                                                                   
              access: read_only
            - attribute_id: 0x0031 # Battery Size
              type: 8BIT_ENUM
              value: 2 # Other 
              access: read_write
            - attribute_id: 0x0033 # Battery Quantity
              type: U8
              value: 1
              access: read_write
            - attribute_id: 0xfffd # Cluster Revision
              type: U16
              value: 6
              access: read_only
        - id: BASIC
          attributes:
            - attribute_id: 0x0007 # Power Source
              type: 8BIT_ENUM
              value: 3 # Battery
              access: read_only
```
Even if I remove the `BASIC` cluster configuration and leave just the `power_supply: 0x03`, the "Manage zigbee device" dialog lets me query the `power_source` attribute of the `BASIC` cluster and yields `PowerSource.Battery`, and if I remove the `power_supply: 0x03`, it'll now yield `PowerSource.Unknown`.

Help me understand what needs to happen so that ZHA will report this device as a battery device and successfully display the battery entity data for it.
