### ISSUE TITLE
ESPHome 2025.6.0 broke template sensor support on endpoints.

### ISSUE THREAD

**Issue by MTRNord** [luar123/zigbee_esphome#47]
Prior to updating this code worked fine but since updating I get this config validation error:

```
Failed config

zigbee: [source /config/esphome/esphome-web-aea8c8.yaml:161]
  id: zb
  name: Marcel CO2 Ampel Büro
  power_supply: 1
  endpoints: 
    - num: 1
      device_type: TEMPERATURE_SENSOR
      clusters: 
        - id: CARBON_DIOXIDE_MEASUREMENT
          attributes: 
            - attribute_id: 0
              type: SINGLE
              device: co2val
              report: True
              value: nan
              scale: 1.0
              access: 0
            - attribute_id: 2
              type: SINGLE
              report: True
              value: 5000.0
              scale: 1.0
              access: 0
          role: SERVER
        - id: TEMP_MEASUREMENT
          attributes: 
            - attribute_id: 0
              type: S16
              report: True
              device: tempval
              scale: 100.0
              value: 0
              access: 0
          role: SERVER
    - num: 2
      device_type: ON_OFF_OUTPUT
      clusters: 
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 85
              type: BOOL
              report: True
              
              ID 'button_green' of type template_::TemplateBinarySensor doesn't inherit from sensor::Sensor. Please double check your ID is pointing to the correct value.
              device: button_green
              id: zb_green_switch
              scale: 1.0
              value: 0
              access: 0
          role: SERVER
    - num: 3
      device_type: ON_OFF_OUTPUT
      clusters: 
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 85
              type: BOOL
              report: True
              
              ID 'button_yellow' of type template_::TemplateBinarySensor doesn't inherit from sensor::Sensor. Please double check your ID is pointing to the correct value.
              device: button_yellow
              id: zb_yellow_switch
              scale: 1.0
              value: 0
              access: 0
          role: SERVER
    - num: 4
      device_type: ON_OFF_OUTPUT
      clusters: 
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 85
              type: BOOL
              report: True
              
              ID 'button_red' of type template_::TemplateBinarySensor doesn't inherit from sensor::Sensor. Please double check your ID is pointing to the correct value.
              device: button_red
              id: zb_red_switch
              scale: 1.0
              value: 0
              access: 0
          role: SERVER
  on_join: 
    - then: 
        - logger.log: 
            format: Joined network
            args: []
            level: DEBUG
            tag: main
  manufacturer: esphome
  date: 20250619
  version: 0
  area: 0
  router: False
```

Not sure if this is an error needing fixes here or if it is an error in esphome upstream.

The buttons are defined as:

```
binary_sensor:
  - platform: template
    name: "Red Status LED"
    id: button_red
    internal: true
    on_state:
      - zigbee.report: zb
  - platform: template
    name: "Yellow Status LED"
    id: button_yellow
    internal: true
    on_state:
      - zigbee.report: zb
  - platform: template
    name: "Green Status LED"
    id: button_green
    internal: true
    on_state:
      - zigbee.report: zb
```
